#!/bin/sh

FILES=$(git diff --cached --name-only --diff-filter=ACMR)
[ -z "$FILES" ] && exit 0

echo "$FILES" | xargs pnpm exec prettier --write --ignore-unknown

JS_TS_FILES=$(echo "$FILES" | grep -E '\.(js|ts|tsx)$' || true)

if [ -n "$JS_TS_FILES" ]; then
  echo "$JS_TS_FILES" | xargs pnpm exec eslint --fix --max-warnings=100 || true
fi

git add $FILES